base/deployment.yaml

This deployment just wraps the third-party image
`otel/opentelemetry-collector-contrib:0.75.0` so annotating this with `tags.oss=true`. The other tags are just the required basics.
Ticket: DENA-87

Add annotations for collector deployment

---

README.md

Without a protocol the rendered markdown would link to (the non-existent)
<https://github.com/utilitywarehouse/opentelemetry-manifests/blob/main/opentelemetry.io>

Fix link to OpenTelemtry in README

---

tempo/base/config.yaml

Seems 30s is not currently enough for some queries.
Example: [query](https://grafana.prod.aws.uw.systems/explore?orgId=1&left=%7B%22datasource%22:%22tempo%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22tempo%22%7D,%22queryType%22:%22traceql%22,%22limit%22:20,%22filters%22:%5B%7B%22id%22:%224baf53c8%22,%22operator%22:%22%3D%22,%22scope%22:%22span%22%7D%5D,%22query%22:%22d72cdfe39b870b8edde3531780f7b1fd%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D)

Allow 1m for looking up trace by id

---

tempo/base/query-frontend/deployment.yaml

We were using `1m`  for limit, thus the CPU was getting throttled a lot.
After this, the query speed got 4x better

Fix resources definition for query-frontend 

---

tempo/base/config.yaml
tempo/base/querier/deployment.yaml

- Updated GRPC send msg size to retrieve bigger traces
- Increased max memory for queriers to allow big traces to be retrieved.

DENA-249: Retrieve bigger traces

---

tempo/base/metrics-generator/deployment.yaml

The CPU was being throttled this morning: https://utilitywarehouse.slack.com/archives/C050DMK37QT/p1695106216467179
Regular usage is around 150m https://grafana.prod.aws.uw.systems/d/faeKgjeMk/kubernetes-pod-usage-vs-resource-app?orgId=1&var-namespace=otel&var-app=tempo-metrics-generator&var-pod=All&var-app_kubernetes_io_name=All&from=1695097737468&to=1695107700035

Add requests for metrics generator

---

tempo/base/ingester/statefulset.yaml

This is importing some changes made from downstream `kustomization`s. We noticed these pods using a very small amount of CPU, even when in a high traffic setting (i.e. during times of very high memory usage).

Lower CPU requests on tempo ingester pods

---

tempo/base/ingester/statefulset.yaml

Follow up from ffc209244ad2fbcef9d5dfa65b82c7e8822f0d41, we wanted to
distinguish between:
* 0m meaning: we've seen it use a small, insignificant amount of CPU, vs.
* 20m meaning: we have measured it, and it idles at 0.02 CPU shares,
we've made no such measurements

Further lower ingester CPU requests

---

tempo/base/config.yaml
tempo/base/kustomization.yaml

v2.3.0 release with basic change to support new (clearer) override config.
Release does not yet make use of new features from vParquet3.

Tempo v2.3.0

---

tempo/base/config.yaml

Enable resource & span dedicated columns to help improve query performance.
Here I've taken combined a good guessing by analysing dev & prod blocks and combined. While we could get dedicated environment config, I'm aiming in this first pass to ease operating while we collect more data.
Steps I took to analyse the block...
```
> aws s3 sync s3://{bucket}/single-tenant/00061d04-60c9-48d6-9d67-93c572e3a80d .
> tempo-cli analyse block --backend=local --bucket=. single-tenant 00061d04-60c9-48d6-9d67-93c572e3a80d
```

Use vParquet3 dedicated columns

---

tempo/base/config.yaml

We had a spike yesterday.
This should make the ingesters cope better with the load.
For full context and readings see: https://utilitywarehouse.slack.com/archives/C02QB672AKH/p1700194889166819

ingester: decrease the max_block_duration to 5m from 15m and max_block_bytes to 100 MB from 500 Mb

---

tempo/base/config.yaml

Cleans up a few config items after the v2.4 release notes highlighted a few points.
Commits explain the why.
Hopefully this should be the last step before promoting the release to production.

Tempo v2.4.0 refinement

---

otel-collector/deployment.yaml

- https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.93.0
- https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.94.0
- https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.95.0
Key change for us in `v0.93.0`:
```
kafkareceiver: The Kafka receiver now exports some partition-specific metrics per-partition, with a partition tag (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30177)
The following metrics now render per partition:
kafka_receiver_messages
kafka_receiver_current_offset
kafka_receiver_offset_lag
```
Apart from that keeps things up to date, brings in bug fixes & improves OTTL ahead of us looking at tail-sampling

OTel collector v0.95.0

---

otel-collector/deployment.yaml

This might solve our issue from https://linear.app/utilitywarehouse/issue/DENA-490/otel-collector-failed-to-enqueue-spans-investigate-reason
Tested this in dev-merit. Will need a bit of config updates around the endpoints

otel collector: upgrade to 0.107.0

---

tempo/base/kustomization.yaml

https://github.com/grafana/tempo/releases/tag/v2.5.0
Expected breaking change which the overlay to his base can look to apply

Tempo v2.5.0

---

tempo/base/distributor/deployment.yaml
tempo/base/distributor/hpa.yaml
tempo/base/distributor/kustomization.yaml
tempo/base/ingester/hpa.yaml
tempo/base/ingester/kustomization.yaml
tempo/base/ingester/statefulset.yaml

Also adjusted a bit the default requests and limits for them. 
It is especially important to have non 0 requests specified, now that HPA is in place, as that's the value that HPA checks against

DENA-908: tempo: add horizontal pod autoscaler to distributor and ingester

---

tempo/base/compactor/deployment.yaml
tempo/base/distributor/deployment.yaml
tempo/base/ingester/statefulset.yaml
tempo/base/metrics-generator/statefulset.yaml
tempo/base/querier/deployment.yaml
tempo/base/query-frontend/deployment.yaml

GOMEMLIMIT is now the recommended way since Go 1.20

Stop using ballast

---

README.md
otel-web-collector/README.md
otel-web-collector/deployment.yaml
otel-web-collector/example_config.yaml
otel-web-collector/kustomization.yaml

Importing the config from what's defined in our running manifests. This is so we can have more of the moving parts for our OTEL stack defined in this repo.
Ticket: DENA-950

Import basic manifests for `web-collector`

---

tempo/base/metrics-backend/config/prometheus.yaml
tempo/base/metrics-backend/disruption-budget.yaml
tempo/base/metrics-backend/kustomization.yaml
tempo/base/metrics-backend/services.yaml
tempo/base/metrics-backend/statefulset.yaml

This backend is Prometheus, this is to:
* keep the pieces of our Tempo setup defined in one place
* avoid duplicate manifests across environments (just inherit from this
one)
This is just a copy of the manifest currently running on one of our
environments with a single change: the `storage.tsdb.retention.time` is
populated from an env var (docs[1]), rather than directly in the args.
This is because this var changes across envs and we can easily patch
environment variables but not specific arguments
Some files were also renamed and certain entities extracted to their own
file
[1] https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments

Move Tempo metric backend up from manifests

---

otel-collector/deployment.yaml

By setting `GOMAXPROCS` to the number of available CPUs available to the pod via the 'downward API'[1]. This is based on[2], otherwise the collector will use `runtime.NumCPU` (i.e. number of processors available to the _node_) when setting up batch processing.
Some experimentation: I modified our pubsub producer to start producing _lots_ of messages (and hence events) to stress test the collector, before this change, once the collector queue was full it seemed like nothing, even adding a bunch more pods, would resolve the issue, here is the rate of span production:
Which quickly filled up the collector queue:
However, even if I added a bunch more pods they would just start throttling:
Though the CPU usage never looked alarming (i.e. it never approached the limit of `2`):
With this change …

Fix CPU throttling on collector during high traffic

---

README.md

The `collector-web` outputs to the `collector` in AWS, not directly to Kafka

Update output for collector-web in diagram

---

tempo/base/config.yaml

Often when I'm opening a few tabs from clicking on search results, some will fail with a 429 error. According to the docs, this is expected more often than we'd realised after upping `concurrent_jobs` to scale querying in a previous PR.
From the docs:
When increasing concurrent_jobs, also increase the queue size per tenant, or search requests will be cause 429 errors. This is the total number of jobs per tenant allowed in the queue.

Reduce 429 errors from multiple in-flight searches

---

tempo/base/metrics-backend/kustomization.yaml

As pointed out by @matthewhughes-uw:
https://github.com/utilitywarehouse/opentelemetry-manifests/pull/50#pullrequestreview-2339324128
Align with Infra:
https://github.com/utilitywarehouse/thanos-manifests/blob/6b31fa1a457998b25565d1c85acac42ac068626e/base/prometheus/kustomization.yaml#L8C13-L8C20

Prom v2.54.1 to align with Infra
